services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  springboot-app:
    build: .                          # builds from your Dockerfile
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092   # points to kafka container
      SERVER_PORT: 8081

#  jenkins:
#    image: jenkins/jenkins:lts
#    user: root  # Gives Jenkins permissions to read the docker socket
#    ports:
#      - "9090:8080"  # Fixed to map your localhost:9090 to Jenkins internal 8080
#    volumes:
#      - jenkins_home:/var/jenkins_home
#      # This is the magic link that lets Jenkins use your MacBook's Docker daemon:
#      - /var/run/docker.sock:/var/run/docker.sock
#
## This is the missing piece that tells Docker to create the persistent volume!
#volumes:
#  jenkins_home: